#!/bin/bash


if #1
then
    if #2

    else
        if #3
        
        elif
            if #4
            then

            else

            fi #1
        fi #2
    fi #3
elif [[ 1.2 ]]
then
    if #5
    then
        if #6

        elif
        then

        elif
        then
            if #7
            then

            fi #4
        fi #5
    else

    fi #6
elif [[ 1.3 ]]
then

else

fi #7
