
# Send notifications from WSL to Windows
# https://github.com/stuartleeks/wsl-notify-send
notify-send() { wsl-notify-send.exe --category $WSL_DISTRO_NAME "${@}"; }
# Example notification
alias makeit='<compilation> && notify-send \"Compilation done!\"'

# cat with color
alias ccat='highlight -O ansi --force'
# less with color
lless()
{
   ccat "$1" | less -R
}

# PS1 adding @BuildServer in orange after username
# PS1_customSecond='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u\[\033[00m\]\[\033[38;5;214m\]@BuildServer\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$'
