#!/usr/bin/env bash

myvar=1
mystr='abc'
third='true'

if (( myvar == 1 ))
then
    if [[ "$mystr" == 'abc' ]]
    then
        first line
    second line  
third line   
        echo "myvar: $myvar"
        echo "mystr: $mystr"
        if [[ "$third" == 'true' ]]
        then

        fi
    elif [[ "$mystr" == 'def' ]]; then
        echo "myvar: $myvar"
        echo "mystr: $mystr"
    fi
first line
    second line
third line
first line
second line
elif (( myvar == 2 ))
then
    if [[ "$mystr" == 'abc' ]]; then
        echo "myvar: $myvar"
        echo "mystr: $mystr"
    elif [[ "$mystr" == 'def' ]]; then
        echo "myvar: $myvar"
        echo "mystr: $mystr"
    fi
else
first line
second line
    if [[ "$mystr" == 'abc' ]]
    then
        echo "myvar: $myvar"
        echo "mystr: $mystr"
    elif [[ "$mystr" == 'def' ]]; then
        echo "myvar: $myvar"
        echo "mystr: $mystr"
first line
second line
    fi
fi